security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
                
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/auth
            stateless: true
            user_checker: App\Security\UserChecker
            json_login:
                check_path: /api/auth
                username_path: email
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            user_checker: App\Security\UserChecker
            entry_point: jwt
            jwt: ~
            refresh_jwt:
                check_path: /api/token/refresh 
            logout:
                path: api_token_invalidate
                
        admin:
            pattern: ^/admin
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: admin
                always_use_default_target_path: true
                enable_csrf: true
            logout:
                path: app_logout

    access_control:
        # Auth public urls
        - { path: ^/api/(auth|token/refresh|register)$, roles: PUBLIC_ACCESS }
        - { path: ^/api/verify/email$, roles: PUBLIC_ACCESS }

        # Form public urls
        - { path: ^/api/form-meta$, roles: PUBLIC_ACCESS }
        - { path: ^/api/form/all$, roles: PUBLIC_ACCESS }
        - { path: ^/api/form/\d+/comments$, roles: PUBLIC_ACCESS }
        - { path: ^/api/form/\d+/like/count$, roles: PUBLIC_ACCESS }
        - { path: ^/api/form/\d+$, roles: PUBLIC_ACCESS }
        - { path: ^/api/form/\d+/title$, roles: PUBLIC_ACCESS }
        - { path: ^/api/odoo/template$, roles: PUBLIC_ACCESS }

        # Other public urls
        - { path: ^/api/home$, roles: PUBLIC_ACCESS }
        - { path: ^/api/search$, roles: PUBLIC_ACCESS }
        - { path: ^/api/search/meta$, roles: PUBLIC_ACCESS }
        - { path: ^/docs, roles: PUBLIC_ACCESS }

        # All other routes are protected
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
